### ISSUE TITLE
initializePlugin function failed

### ISSUE THREAD

**Issue by chrisperrella** [dsparrow27/mayaPlugins#3]
Hey Dave, 

When I compile and load your node, I receive the following errors

```
# Error: pymel : Failed to get controlCommand list from MathNodes # 
# Error: pymel : Failed to get modelEditorCommand list from MathNodes # 
# Error: pymel : Failed to get command list from MathNodes # 
# Error: pymel : Failed to get constraintCommand list from MathNodes # 
# Error: pymel.core : Failed to get depend nodes list from MathNodes # 
```

How can I resolve these? MathNodes is the name of the solution.

**Comment by dsparrow27** [comment]
hmm, i haven't recompiled these for a while, ill need some time to test.

**Comment by dsparrow27** [comment]
I have a second branch `fixes`, which should hopefully fix this issue, plus has more angular nodes, bug fixes etc. 
Ill merge it into master once i finish testing each node, hopefully this week.

**Comment by dsparrow27** [comment]
Should all be fixed, tested in maya 2018
